CREATE TABLE `comb_advplatform_daily_merge_t1e1_train` (
  `dt` datetime NOT NULL,
  `impression` bigint(20) DEFAULT NULL COMMENT '曝光量',
  `click` bigint(20) DEFAULT NULL COMMENT '点击量',
  `activation` bigint(20) DEFAULT NULL COMMENT '激活量',
  `clk_ratio` decimal(10,8) DEFAULT NULL COMMENT '点击率',
  `clk_flag` char(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '按照行业、媒体、标的物划分后数据的四分位值（这三项内部点击率不均衡，且广告投放前优化师已经确定了这三项，因此需要组合标记）',
  `day_type` tinyint(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '1 工作日，0 休息日，组合优化项，需要onehot',
  `ind_first_industry_id` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '一级行业id',
  `ind_first_industry_name` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '一级行业名称，组合优化项，需要onehot',
  `adg_site_set` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '投放站点集合，组合优化项，需要onehot',
  `adg_product_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标的物类型，创建campaign时确定，广告组和创意需遵从，组合优化项，需要onehot',
  `tag_age` varchar(25) COLLATE utf8mb4_unicode_ci COMMENT '优化师设置的年龄定向条件，如14-50，不代表真实曝光情况',
  `tag_age_0_17` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_18_23` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_24_30` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_31_40` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_41_50` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_51_65` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_age_66_127` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，遵循广告平台方法离散分组，定向报表中统计出来的真实年龄曝光量比例',
  `tag_gender` varchar(25) COLLATE utf8mb4_unicode_ci COMMENT '优化师设置的性别定向条件，不代表真实曝光情况',
  `gender_FEMALE` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实性别曝光量比例',
  `gender_MALE` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实性别曝光量比例',
  `tag_gloc_regions` varchar(500) COLLATE utf8mb4_unicode_ci COMMENT '优化师设置的地区定向条件，不代表真实曝光情况',
  `region_110000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（北京）',
  `region_120000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（天津）',
  `region_130000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（河北）',
  `region_140000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（山西）',
  `region_150000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（内蒙）',
  `region_210000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（辽宁）',
  `region_220000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（吉林）',
  `region_230000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（黑龙）',
  `region_310000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（上海）',
  `region_320000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（江苏）',
  `region_330000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（浙江）',
  `region_340000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（安徽）',
  `region_350000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（福建）',
  `region_360000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（江西）',
  `region_370000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（山东）',
  `region_410000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（河南）',
  `region_420000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（湖北）',
  `region_430000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（湖南）',
  `region_440000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（广东）',
  `region_450000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（广西）',
  `region_460000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（海南）',
  `region_500000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（重庆）',
  `region_510000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（四川）',
  `region_520000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（贵州）',
  `region_530000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（云南）',
  `region_540000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（西藏）',
  `region_610000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（陕西）',
  `region_620000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（甘肃）',
  `region_630000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（青海）',
  `region_640000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（宁夏）',
  `region_650000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（新疆）',
  `region_710000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（台湾）',
  `region_810000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（香港）',
  `region_820000` decimal(6,5) DEFAULT NULL COMMENT '组合优化项，定向报表中统计出来的真实省份曝光量比例（澳门）',
  `tag_business_interest` varchar(255) COLLATE utf8mb4_unicode_ci COMMENT '优化师设置的商业兴趣定向条件，不代表真实曝光情况',
  `buss_1` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（教育）',
  `buss_2` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（旅游）',
  `buss_3` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（金融）',
  `buss_4` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（汽车）',
  `buss_5` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（房产）',
  `buss_6` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（家居）',
  `buss_7` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（服饰鞋帽箱包）',
  `buss_8` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（餐饮美食）',
  `buss_9` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（生活服务）',
  `buss_10` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（商务服务）',
  `buss_11` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（美容）',
  `buss_12` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（互联网/电子产品）',
  `buss_13` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（体育运动）',
  `buss_14` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（医疗健康）',
  `buss_15` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（孕产育儿）',
  `buss_16` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（游戏）',
  `buss_21` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（政法）',
  `buss_25` bigint(20) DEFAULT NULL COMMENT '组合优化项，按照商业兴趣数量均分的曝光量比例（娱乐休闲）',
  `ad_space` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '广告位，组合优化项，需要onehot（adc_drp*数据项较稀疏，暂不考虑）',
  `adc_form_size` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '素材尺寸，组合优化项，按面积四分位onehot为大、中、小',
  `adc_form_detail` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '素材类型，组合优化项，需要onehot',
  `ade_image_hash` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片hash，不作为组合优化项（需根据组合优化规则结果反查验证，以确定是否优化规则的可靠性）',
  `ade_title` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '广告文案，不作为组合优化项（需根据组合优化规则结果反查验证，以确定是否优化规则的可靠性）',
  KEY `idx1` (`dt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


